language: python
python:
- "3.6"
dist: trusty

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial

env:
- PEP8_IGNORE="E221,E501,W504,W391,E241"

# command to install dependencies
install:
- pip install --upgrade pip setuptools
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
- export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
- coverage run --source=telerembash $(which nosetests) -v --with-doctest tests/ --exclude-dir tests/nonci/
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coverage report --show-missing --fail-under=40 ; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pycodestyle --ignore=$PEP8_IGNORE  --exclude=tests,.venv -r --show-source . ; fi
# For convenience, make sure simple test commands work
- python setup.py develop
# - py.test
# - nosetests -e tests.nonci.*

# load coverage status to https://coveralls.io
after_success:
- 'echo travis-python: $TRAVIS_PYTHON_VERSION'
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install coveralls; COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls ; fi

notifications:
  email: false

deploy:
  provider: pypi
  username: kpe
  password:
    secure: "o9y3rFGcc6tCf4kDnkOqENQGwOhIHgnCQxyB9JwUcWwEZwjvPJxHKBpYJ3PLyaDMu1ThrIwhOmMF1V+Jq2OuWAKkggZKS98f/52gZLZzcG5vswuB1vSSi31u7fDuobXcRiGd2Ne20FOo5jhUDBQKt6bNd+0aGucIAsV9tmWBeiEUSvz6RTs8GcdONEUrYr5yUStCWyNISAgwjqrtl7RtfUkQm+mzAOzgSbNzRAJZkhNqN2BQVXXq7NB8vjnHptlEQOdSQ7u9vRSBReneJyQy50kOlwK/N59rTYkEG/8N3bX4FqXuBY+hAe7geEUVhU8SJKRoQdTwsL0gt4Z0CJVGHLhALgZcpw5LhhdZoIAk9zReoKVub1lO5tkmw7SBMCEkQh7paCEEefPp00DVUFCXA1Ie8CidtiIRUUTVHjOqxkAzNQTZm3C7fK/Xa/xVp+NEfM+zWzDaJeoszvAEwqLBZPM7/cif5oIBgOU93UF0+BFxXWWW3IyKeEQV2KawucKq0aA0e88Q2FlmRGhWmvy2c3v1y7aodliEL0qcEGvYzFW5dFl0vFFaY4UWOO20avHyfsZL+Xzy/CAK4ErCV4zr/gxmUUavzxkaWuUC5jSUil0RK39Mg1qdOYFcmILlSlAetP54Mhh2KlPuIsL/pmafdB2U6eZMR0Av9npQTmrDK2U="
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  skip_existing: true
