language: python
python:
- "3.6"
dist: trusty

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
  - python: 3.7
    dist: xenial

env:
- PEP8_IGNORE="E221,E501,W504,W391,E241"

# command to install dependencies
install:
- pip install --upgrade pip setuptools
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
- export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
- coverage run --source=telerembash $(which nosetests) -v --with-doctest tests/ --exclude-dir tests/nonci/
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then coverage report --show-missing --fail-under=40 ; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pycodestyle --ignore=$PEP8_IGNORE  --exclude=tests,.venv -r --show-source . ; fi
# For convenience, make sure simple test commands work
- python setup.py develop
# - py.test
# - nosetests -e tests.nonci.*

# load coverage status to https://coveralls.io
after_success:
- 'echo travis-python: $TRAVIS_PYTHON_VERSION'
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install coveralls; COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls ; fi

notifications:
  email: false

deploy:
  provider: pypi
  username: kpe
  password:
    secure: qNxowCRNykP95C0QDFlUVbDVJ6cny/xqN3ibqgi0ogSZDfq8aXAhUFRz5ZzOLLdaytGPiS8qdQv32Nf6IxsvQhb00MRE9ZBqXDn5dWeyWw7/Zgov0RAgHW+BbUEa7C8oSiQyZgYvxtefEH00LHu2i1NVbHMe6JZoayk5QuFryJxZq5sUq0DoRoIPztHbvCxcNBFaRZt8b6v85i7jEekGmBFeLs8EK4oybQwJopmb3Gu7l6sK4Al1sXDwFIOvZtJGUJcncjaHI2h9vQ7DIHUN3lrW/NBoj3Mu5ydShc3JFlHFe2mt1aGhW7xJT8/ixRbIhuVE2EAihj6kRQie9ic52oIK5tGvgeefuklAscHc6KBO/IhlVHsAwA0gb3Wzf3iW6+9jq+RT6IBdrorziJ5TbmMyhgZocIwAaqCNvx5lAdPRChQBul4RK/sGLTf6NsV6IDshcsOl5MbHp9dNR1md+qJFvtJU5hQU+SF5ZSSAvA3TgKgp3VaF+PpQy6/SKOv1bMk413aMMbSWgXV2QpEAdr7gCFGbjp17Bgtyv0of+3kYaBEkw6aEjDphSrxa8+czwn8FuEhZ6NMsV9eigEGCOHR+4wkHwO/UEKoSvEDzcXiPZmIIFrvHNcPmv4IWZ6sCX3IagwSMIG0RUUMKVONIkjUCOHNFkEq73NY/bhV1c1A=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  skip_existing: true
